### ISSUE TITLE
ObjC Object $ivars type resolution fails with: Unable to handle type " 

### ISSUE THREAD

**Issue by leonjza** [frida/frida-objc#18]
Consider the following sample code (from the frida-objc-playground):

```javascript
'use strict';

const ObjC = require('frida-objc');

global.run = function () {
    const clazz = "NSString";
    return ObjC.chooseSync(ObjC.classes[clazz]).map((instance) => {
        return {
            ivars: instance.$ivars,
        };
    });
};
```

Running this will result in a Frida exception as follows:

```
frida.core.RPCException: Error: Unable to handle type "
    at readType (../index.js:2192:19)
    at readType (../index.js:2182:34)
    at parseType (../index.js:2125:16)
    at findIvar (../index.js:1180:30)
    at Object.get (../index.js:1134:38)
    at ../index.js:1219:36
    at Array.reduce (<anonymous>)
    at Proxy.toJSON (../index.js:1218:20)
    at JSON.stringify (<anonymous>)
    at value (frida/runtime/core.js:48:1)

```

## debugging

I modified `frida-objc` to add extra [`log()`](https://gist.github.com/leonjza/1f285abdfbfd508107351775b5029908) statements for the [`readType()`](https://github.com/frida/frida-objc/blob/master/index.js#L2125) method to follow recursion, which results in output as follows. The first being a successful type parse for a reasonably complex type string. 

```
Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",0]
TYPE => undefined
ID => {


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",14]
TYPE => undefined
ID => b


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",27]
TYPE => undefined
ID => b


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",37]
TYPE => undefined
ID => b


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",45]
TYPE => undefined
ID => b


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",58]
TYPE => undefined
ID => b


Cursor => ["{?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27}",62]
TYPE => undefined
ID => b

Resolved from type: {?="isStorage"b1"isUnicode"b1"hasBOM"b1"swap"b1"immutable"b1""b27} => {"type":["int","int","int","int","int","int"],"size":24}
```

However, the following is an example type that fails to parse:

```
Cursor => ["(?="d"{?="data"@"NSData""dataBytes"*}"s"{?="storage"^{__CFStorage}})",0]
TYPE => undefined
ID => (


Cursor => ["(?="d"{?="data"@"NSData""dataBytes"*}"s"{?="storage"^{__CFStorage}})",3]
TYPE => undefined
ID => "
```

I can't seem to be able to fix what I suspect is a parser bug here. Please help :)

**Comment by dweinstein** [comment]
@leonjza does this only happen when you're attaching to a specific app? Are you able to reproduce it on MacOS too? I created a test case for it here https://github.com/frida/frida-objc/commit/36b760797a148d9ff74a63d8e437ffae1c5b37e7 but currently this test is passing for me.

**Comment by leonjza** [comment]
Shared a target app privately where this could be reproduced. I have not tested on macOS yet, but will share results when I can. Thanks for taking time for this :)
